#!/bin/sh
#
# @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @copyright Copyright (c) 2014-2016 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

XPATH="/config/services/remotemount/mount"

index=$(omv_config_get_count "${XPATH}")
while [ ${index} -gt 0 ]; do

    type=$(omv_config_get "${XPATH}[position()=${index}]/mounttype")

    if [ "${type}" = "ftpfs" ]; then

        username=$(omv_config_get "${XPATH}[position()=${index}]/username")

        if [ -n "${username}" ]; then
            server=$(omv_config_get "${XPATH}[position()=${index}]/server")
            password=$(omv_config_get "${XPATH}[position()=${index}]/password")
            echo "machine ${server}"
            echo "login ${username}"
            echo "password ${password}"
            echo ""
        fi
    fi

    index=$(( ${index} - 1 ))
done