#!/bin/bash

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

remove_action() {
    # Activate trigger to purge cached files.
    dpkg-trigger update-fixperms
}

case "$1" in
    purge)
        XPATH="/config/services/remotemount"
        XPATH_MOUNT="${XPATH}/mount"

        remove_action

        # delete mntent entries
        count=$(omv_config_get_count "${XPATH_MOUNT}")
        index=1
        while [ ${index} -le ${count} ]; do
            # get mntent uuid
            mntentref=$(omv_config_get "${XPATH_MOUNT}[position()=${index}]/mntentref")

            # get mount directory and lazy unmount (in case filesystem is in use)
            dir=$(omv_config_get "/config/system/fstab/mntent[uuid='${mntentref}']/dir")

            if [ -n "${dir}" ]; then
                echo "Unmounting ${dir} directory..."
                if mount | grep ${dir} > /dev/null; then
                    umount -l ${dir}
                fi
            fi

            # delete mntent entry
            omv_config_delete "/config/system/fstab/mntent[uuid='${mntentref}']"

            index=$(( ${index} + 1 ))
        done

        omv_config_delete ${XPATH}

        # Regenerate fstab
        omv-salt deploy run fstab

        # remove credential files
        rm -f /root/.cifscredentials-*
        
        # remove secrets files
        if [ -f "/etc/davfs2/secrets.orig" ]; then
            rm -f "/etc/davfs2/secrets"
            cp "/etc/davfs2/secrets.orig" "/etc/davfs2/secrets"
        fi
    ;;

    remove)
        remove_action
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
