#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale

        # Initialize and migrate configuration database.
        echo "Updating configuration database ..."
        omv-confdbadm create "conf.service.remotemount"
        if [ -n "$2" ]; then
            omv-confdbadm migrate "conf.service.remotemount" "${2}"
        fi
        
        #copy secrets file
        if [ ! -f "/etc/davfs2/secrets.orig" ]; then
            if [ -f "/etc/davfs2/secrets" ]; then
                cp "/etc/davfs2/secrets" "/etc/davfs2/secrets.orig"
            fi
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
